use antonioc;
CREATE EXTERNAL TABLE IF NOT EXISTS antonioc.tienda(
 IdTienda string,
 Sucursal string,
 Distrito string,
 Tipo string,
 DistritoTipo struct<Distrito:STRING,Tipo:string>
 )
 COMMENT 'Tabla tienda'
 ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
 COLLECTION ITEMS TERMINATED BY ','
 MAP KEYS TERMINATED BY ':'
 LOCATION '/antonioc/empresa/tienda'
 tblproperties("skip.header.line.count" = "1");